name: Build and test

on: [push, pull_request]

jobs:
  build_and_test:
    environment: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: git checkout
        uses: actions/checkout@v5

      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main
      
      - name: Build
        run: nix develop --command go build -v ./...

      - name: Test
        run: nix develop --command go test -v -p 1 ./...