name: Build and test
on: [push, pull_request]
jobs:
  build_and_test:
    environment: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ env.GITHUB_TOKEN }}
            binary-caches = https://cache.nixos.org https://${{ env.CACHIX_CACHE }}.cachix.org
      - uses: cachix/cachix-action@v12
        with:
          name: ${{ env.CACHIX_CACHE }}
          authToken: ${{ env.CACHIX_AUTH_TOKEN }}
      - name: git checkout
        uses: actions/checkout@v1
      - name: Build
        run: nix develop --command go build -v ./...
      - name: Test
        run: nix develop --command go test -v -p 1 ./...
      - name: Push dev shell to Cachix
        run: |
          nix develop --profile nix-purpledb
          cachix push ${{ env.CACHIX_CACHE }} nix-purpledb
