name: Build and test
on: [push, pull_request]
jobs:
  build_and_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ env.GITHUB_TOKEN }}
      - name: git checkout
        uses: actions/checkout@v1
      - name: Build
        run: nix develop --command go build -v ./...
      - name: Test
        run: nix develop --command go test -v -p 1 ./...
